apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - certificate.yaml
  - seal-secrets.yaml
  - repository.yaml
  - release.yaml
  - self-certificate.yaml
  - ca-secret.yaml
  - ingress.yaml
