apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:ZGKaKiwoOgdh9W5sS1rSzCU/yo0icuBBmYWU3agTLqpaHcY2GnGVxP0lSmpRI+jnGkQDOOrlOtw=,iv:exnu0O/dDEQuF3d4OIpD0VyVEty+EXTNJWIg5ZmKHy4=,tag:6GgDsLc4vb0AFwzRmfRS6g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-token-secret
    namespace: cert-manager
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR09oUVVzV3B0ZUR4N25X
            MFpBck8rZnJTcDFEZVcydXUwVEVCNnBiMEFBCk1weVN4c0psaFpkYnErSUlHTUZD
            VmFmbVQ1RElkR0NCa2QxTmtmV25odmcKLS0tIEwzRDRCRm53eklQc3BsQ3VxcXdX
            dm95OGVoNlgvNlI2VWE2RTEvbm9CNzAKHZVFlVD/SYqyI3ST4+fOdv0ziS0xJsFH
            dV9q37HCNf4xf6ToUoIPSFa1yoIJNfaF/47GodfGTwubq/SPbzyazw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-16T02:32:11Z"
    mac: ENC[AES256_GCM,data:YHH5yAMD2qDTq70/FsIILXOHKgMVpdxxYUZFlHRJ4nq7moptHGyInDP+XXKRhRuo5x/HC64wPWFE9+eoUX23nE1xHAzW2EsKqWGpgTsl0HLHi/myba254mGKWxyL1mW6mQTdLYmuvci40ZVG+yJS5cFa3Mb94inPCbZWxlWUBzU=,iv:X/SKuet91rWw4VAw+E59lwcoepW9G+PLexNkfbfO5uY=,tag:9NuK4dcUp/eGhCVq9Xzhlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
