apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 labels:
   prometheus: example-rules
   role: alert-rules
 name: prom
 namespace: monitoring
spec:
 groups:
   - name: "prom.rules"
     rules:
     - alert: trivy_unhealthy
       expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
       for: 30s
       labels:
         severity: critical
       annotations:
         description: Trivy container is unhealthy for more than 30 seconds.
         summary: Trivy unhealthy
         type: Container
     - alert: trivy_missing
       expr: sum by (namespace) (kube_pod_container_info{container=~"trivy-operator-*"}) == 0
       for: 30s
       labels:
         severity: critical
       annotations:
         description: Trivy container is missing for more than 30 seconds.
         summary: Trivy missing
         type: Container
     - alert: trivy_new_critical_vuln
       expr: increase(trivy_image_vulnerabilities{severity="Critical"}[30m]) >= 1
       for: 30s
       labels:
         severity: warning
       annotations:
         description: Trivy found a new CRITICAL vulnerability in a deployed container imgae
         summary: Trivy new CRITICAL vulnerability
         type: Container