apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-auth.yaml
  - secrets.yaml
  - harbor-secret.yaml
  # - image-policy.yaml
  - certificate.yaml
  - release.yaml
