{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- if and (eq ($.Values.service.type | default "ClusterIP") "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "test-app.selectorLabels" . | nindent 4 }}
{{- end }}