apiVersion: v1
data:
    slack_api_url: ENC[AES256_GCM,data:vPjOy5GirsRM8sBAGLPZTfi6UDLdxp6beGSTZKqGs9O0G1xF4qKG/f8EYDWyLeljojAqsz17td/4Mtcz9KLUeoJrZ6V4VqR399zrXWO3B2hTPxLDYUlupX7GJPdgLYUbX+c18epvs2I69v2M,iv:Yqfejjbp0FaNEyJbtw4ysFW6CS76ntCFC69RyZzw31M=,tag:11VprEEhZHPubJiluEht6g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-webhook
    namespace: monitoring
sops:
    age:
        - recipient: age1wnrqha3nhhlmlt5caggm8l7xgf5hzyez646vcave2hvv34yxls7qyar5jr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TitvdExndWFKSUJmMkpu
            U0R4R2RhY1l6RGp4QXdNVUZ6OXBsdE1XU1NNCjNCSkVnb1Z1WHBob2tnQm83SGd6
            MGdtOUN5RnllY0RUYTVBK05WeHhJMEEKLS0tIGJaSWFHNnYzMVFnV3FEWHNPM3hn
            aGs4ZmIzN2xmZ2R1c2E0MVZxWVc2aEkK/1g6vhKRXVKhvvzJy40Bi2cvCTr7UCxt
            CveQl8a/8twhrcT46vI8eBg5fUT+j6hc7yWdlND2EVWlzL5hyOTTkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T21:41:06Z"
    mac: ENC[AES256_GCM,data:9uH+Zy47TDfJSeLcVt+3JysDDR6YD2bwP9Oqrm76QFWvrJfQ4PnV/V7H2+L8p7/bTDy4i4ycEDvy6GFWPSqQwchdeOAGhkwAOyhtOstmemX8qM3IvQH6LcqsR8d6PRXo/bGB1rc1+di7IoCDgpqMXANOMdYjv+LZLR34nBpxBs8=,iv:mOmAKo+fdwOk2j9/BKJBKX+OIb0Hy5uqliYVxaalVwY=,tag:XldGN9drc0WEsEEmGYeVcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
